### ISSUE TITLE
[Issue] NymWallet: Error "Signature was either invalid or not required"

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#4393]
**Describe the issue**
When signing the message for swapping NYM=>BTC via Bity, the pop-up appears "Signature was either invalid or not required" and the transaction doesn't go through

Tried on Windows and MacOS. Used the latest version of the wallet - 1.2.11

**Expected behaviour**
The message should be signed and the transaction go through

**Steps to Reproduce**
Click Buy tab in the wallet
Click Buy NYM
Choose NYM=>BTC
Submit details
Sign the message
Copy the signature and paste it in the field
Pop-up "Signature was either invalid or not required" appears

**Screenshots**
https://prnt.sc/_txbBZ7f9ZOv

**Comment by tommyv1987** [comment]
I've followed the exact same steps above and was not able to reproduce this error; steps as follows:

1. log in to the wallet
2. navigate to buy NYM
3. redirected to the bity page to purchase nym
4. proceeded through the workflow to sign message
5. copied the message to sign pasted it into the nym-wallet
6. copied the output as the wallet displays
7. went back to the bity page inputted the signature and the order id was successful

images attached:
<img width="708" alt="image" src="https://github.com/nymtech/nym/assets/60836166/8852b193-5d83-4e9e-ab1e-c82d6418913e">

<img width="683" alt="image" src="https://github.com/nymtech/nym/assets/60836166/c618521c-34ce-43c3-824d-926f78b7b17c">

please can the user go through the full steps to reproduce and list errors / screenshots as the functionality looks like it's working, trialled on the pre-release of wallet version v1.2.12, i will close the ticket unless commented on, which will then re-open the request

**Comment by andrei100ff** [comment]
I've tried selling NYM using the same functionality and got the same error

**Comment by andrei100ff** [comment]
Any updates with this issue? This feature still doesn't work on desktop app on Windows

**Comment by tommyv1987** [comment]
@andrei100ff we're currently investigating swaps from NYM/BTC using Bity, please bare with us, BTC/NYM is working fine. Once we have an update, we will let you know, hopefully it isn't too long.

**Comment by tommyv1987** [comment]
@andrei100ff this issue is now fixed, you should be able to trade the pairs bilaterally now, thank you for your patience.

**Comment by andrei100ff** [comment]
@tommyv1987 I still have the same error - Signature was either invalid or not required.

**Comment by tommyv1987** [comment]
With the opposite pair NYM/BTC you need to sign the message in a BTC wallet like electrum.

A walkthrough guide here, explains how to sign the message in an Electrum wallet.

https://support.hashkey.com/hc/en-gb/articles/20694247822233-How-to-use-your-personal-wallet-to-perform-sign-message#:~:text=Go%20to%20the%20Electrum%20Personal,%5BSignature%2FVerify%20Message%5D.

To clarify: 
BTC/NYM :- you sign the message in the nym-wallet
NYM/BTC :- you sign the message in a BTC based wallet

Let me know how you get on.
